# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    
fos_ck_editor:
    default_config: default 
    configs:
        default: 
            toolbar: ['Bold', 'Italic']
            styles: 
                -   name:       'Blue Title'
                    element:   'h2'
                    styles: 
                        color: 'blue'