# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    controller:
        filter_action: "liip_imagine.controller.filter_action"
        filter_runtime_action: "liip_imagine.controller.filter_runtime_action"
        redirect_response_code: 301

    driver: "gd"
    filter_sets:
        thumbnail: 
            data_loader: imagine.data_loader.filesystem 
            filters:
                thumbnail:
                    size: [64, 64] 
                    quality: 75
                    mode: outboundcrop