twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@SonataForm/Form/datepicker.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
        

when@test:
    twig:
        strict_variables: true
